version: "3.9"
services:
  backend:
    build: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/cache
    volumes:
      - ./backend:/app
      - ./.cache:/cache
  frontend:
    build: .
    command: sh -c "npm install && npm run dev"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3012:3000"
    volumes:
      - .:/app
    depends_on:
      - backend



